#!/bin/bash
#
# A simple framework for regression testing the convert (budget_test) script
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' 'input file name' 'expected output file name' 'expected std error file name'
#
# Some example test cases are given. You should add more test cases.
#
# CAUTION: Uses temporary files named test_err.txt and test_out.txt
# 
# Sam Scott, McMaster University, 2024
#
declare -i tc=0
declare -i fails=0

# Set dynamic coverage path
export GCOV_PREFIX=$(pwd)
export GCOV_PREFIX_STRIP=$(pwd | tr -cd '/' | wc -c)

############################################
# Run a single test. Runs a given command 
# to check the return value, stdout, and stderr
#
# GLOBALS: tc, fails
# PARAMS: $1 = command
#         $2 = input file name
#         $3 = expected std output file name
#         $4 = expected std error file name
#
# Assumes return value should be 0 if the
# std error file is empty. Otherwise it 
# should be 1.
#
# OUTPUTS: An pass/fail report showing the
# difference between expected and actual
# output on a failure (diff command)
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local INP=$2
    local EX_OUT=$3
    local EX_ERR=$4 

    EX_RET=1
    if [[ $(cat $EX_ERR) = "" ]]; then
        EX_RET=0
    fi
    $COMMAND < $INP > test_out.txt 2> test_err.txt
    RET=$?
    if [[ $RET != $EX_RET ]]; then
        echo "TC $tc Failed"
        echo "Returned $RET"
        echo "-----------"
        fails=$fails+1
        return
    fi
    DIFF=$(diff test_out.txt $EX_OUT)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed Standard Output"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi
    DIFF=$(diff test_err.txt $EX_ERR)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed Standard Error"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi

    echo "TC $tc Passed"
}

##command and flag, stdin, stdout, stderr

#input and output files are stored under directories, the test cases will be modified accordingly

test './budget_test --help' 'input_files/empty.txt' 'output_files/help.txt' 'output_files/empty.txt'
test './budget_test' 'input_files/inp1.txt' 'output_files/out1.txt' 'output_files/empty.txt' #create user
test './budget_test' 'input_files/inp2.txt' 'output_files/out2.txt' 'output_files/empty.txt' #test option 1
test './budget_test' 'input_files/inp3.txt' 'output_files/out3.txt' 'output_files/empty.txt' #test option 2
test './budget_test' 'input_files/inp4.txt' 'output_files/out4.txt' 'output_files/empty.txt' #test option 3 
test './budget_test' 'input_files/inp5.txt' 'output_files/out5.txt' 'output_files/empty.txt' #test option 4
test './budget_test' 'input_files/inp6.txt' 'output_files/out6.txt' 'output_files/empty.txt'
test './budget_test' 'input_files/inp7.txt' 'output_files/out7.txt' 'output_files/empty.txt'
test './budget_test' 'input_files/inp8.txt' 'output_files/out8.txt' 'output_files/empty.txt'
test './budget_test' 'input_files/inp9.txt' 'output_files/out9.txt' 'output_files/empty.txt'
#test './budget_test' 'inp9.txt' 'out9.txt' 'empty.txt'
#rm transaction_logs/auser.txt history_logs/auser.txt
#test './budget_test' 'inp10.txt' 'out10.txt' 'empty.txt'
#rm transaction_logs/auser.txt history_logs/auser.txt
#test './budget_test' 'inp11.txt' 'out11.txt' 'empty.txt'
#rm transaction_logs/auser.txt history_logs/auser.txt
#test './budget_test' 'inp12.txt' 'out12.txt' 'empty.txt'
#rm transaction_logs/auser.txt history_logs/auser.txt

# clean up
rm test_err.txt test_out.txt 
rm transaction_logs/sarah123.txt history_logs/sarah123.txt

# return code
exit $fails