name: Budget System - Test App Utility
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build budget system
        run: make budget_system

      - name: Build test
        run: make budget_test

      - name: Run test script
        run: ./test_script > test_results.txt

      - name: Generate main code coverage
        run: gcov budget_test-* > main_coverage.txt

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

      - name: Upload Coverage Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Main Coverage
          path: ./main_coverage.txt
